// Generated by CoffeeScript 1.4.0
(function() {
  var Player;

  Object.forEach = function(object, callback) {
    var key, value, _results;
    _results = [];
    for (key in object) {
      value = object[key];
      _results.push(callback(value, name));
    }
    return _results;
  };

  Object.size = function(object) {
    var key, size;
    size = 0;
    for (key in object) {
      size++;
    }
    return size;
  };

  Player = (function() {

    function Player(name, clan, id) {
      this.name = name;
      this.clan = clan;
      this.id = id;
    }

    return Player;

  })();

  this.SwissTournament = (function() {
    var nextPlayerId, playerCount;

    function SwissTournament() {}

    playerCount = 0;

    nextPlayerId = function() {
      return "p" + ++playerCount;
    };

    SwissTournament.prototype.players = {};

    SwissTournament.prototype.addPlayer = function(name, clan) {
      var player;
      player = new Player(name, clan, nextPlayerId());
      return this.players[player.id] = player;
    };

    return SwissTournament;

  })();

}).call(this);
